### ISSUE TITLE
camsoda error maybe due to guest?

### ISSUE THREAD

**Issue by tsauce** [beaston02/CamsodaRecorder#1] opened 2017-10-14 04:29 UTC
python3.5 CamsodaRecorder.py
Traceback (most recent call last):
  File "CamsodaRecorder.py", line 75, in <module>
    getOnlineModels()
  File "CamsodaRecorder.py", line 23, in getOnlineModels
    for line in data['results']:
KeyError: 'results'

Getting the above error when trying to connect, it worked for weeks but all of a sudden today getting the above error.

I wonder if maybe it will help to login as a user, (like in the Chaturbate recorder) 

Thoughts?

**Comment by ghost** [comment] 2017-10-17 15:17
I just notice that error as well. I think the way the models are pulled is broken some how

**Comment by beaston02** [comment] 2017-10-21 00:58
Hey, Sorry for the slow reply. Life has been crazy here and I kind of just stepped away from all of this until things calmed down some. 

I normally dont run this script (or any script for camsoda), but I found my IP was blocked within the first few minutes of running it. I was limited on the testing I could do because of this, but I changed the script to use Google Chromes User-Agent (so it looks like your browsing in chrome), and a couple of other things. I have it running on a VPS for maybe 20 minutes or so now with no problems. I cant say it is completely fixed, but I will leave it running for now and see what happens. I assume my IP will be unblocked after some period of time, and Ill look at cleaning up the code more and adding a config file, but for now, this will hopefully work. 

If it does not work,  try going to camsodas site and see if it loads. If so, report back to me letting me know, otherwise, see if you can get a new IP address assigned to you (if your ISP has dynamic IPs, you can usually "drop" your ip in your routers web interface and a new one will be assigned - a reboot of the modem/router does not do this).

**Comment by ghost** [comment] 2017-10-21 02:00
I don't think my Ip is blocked

root@ssdnodes-41573:~# python3.5 /root/Campop/CamsodaRecorder.py
Traceback (most recent call last):
  File "/root/Campop/CamsodaRecorder.py", line 80, in <module>
    getOnlineModels()
  File "/root/Campop/CamsodaRecorder.py", line 26, in getOnlineModels
    with r.get(url, headers=headers) as url:
AttributeError: __exit__

**Comment by beaston02** [comment] 2017-10-21 02:04
I changed from the urllib module to the requests module. Can you make sure you have it installed? 

Python3.5 -m pip install requests

I'm away from my computer now, so I'll look into it more if that doesn't work, but hopefully it's that simple.

**Comment by tsauce** [comment] 2017-10-21 02:05
Totally get it. Life gets in the way. Thanks. I’ll check this later. But
the chaturbate one is great. !!

**Comment by ghost** [comment] 2017-10-21 02:09
Requirement already satisfied: requests in /usr/lib/python3/dist-packages

root@host:~# python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06)

**Comment by beaston02** [comment] 2017-10-21 02:18
@tsauce, thanks for understanding! 

@forsomefun, thanks for trying that. I'm not surprised that didn't do it (should have errored out earlier if that was the case), but hoped we would get lucky!!! Lol. 

I'm replying from my phone now so didn't dig into the posted code too much, but nothing caught my eye. I'll look into this more later when I get a chance (tonight or tomorrow morning). Unfortunately, that error doesn't give much info.

**Comment by tsauce** [comment] 2017-10-21 03:44
Working! Going to play around with it more. Thanks again beaston02!

**Comment by rpseleven** [comment] 2017-10-22 10:17
This _could_ be caused by automatic IP bans due to what they see are aggressive/preiodic requests every thirty seconds. I bumped line 81, the timing loop all the way up to 180 seconds (3 minutes), and have been running for over 24 hours. Not ideal for catching models, but it works, so far, without an IP ban.

So instead of:
`        for i in range(30, 0, -1):`
Bump it up to:
`        for i in range(180, 0, -1):`

**Comment by beaston02** [comment] 2017-10-22 12:21
@rpseleven, that was one of my concerns. I plan to create a config file and would include an interval setting so others can specify the time between checks more easily. In my testing, from a few different IP addresses, I was banned almost immediately (a minute or two tops). I believe it was caused by the user-agent though. I've ran it for over a day on a few machines with no issue now that I've specified the user-agent (as well as other changes like using the same session so cookies are retained, and using their own site as the referrer). That doesn't mean that won't change and they won't become more aggressive of course, but for now it seems to be working well.

**Comment by ghost** [comment] 2017-10-22 22:30
I am on a headless machine
I wonder if that is part of my issue 
it seems that other people are able to run this program without issues

It is ubunut 16.04
Python3 

I just have the dependcies from all the recorders install plus the default ones

**Comment by beaston02** [comment] 2017-10-23 17:10
You are the only one I'm aware of who is currently having this issue. I've tested it on 5 or 6 systems with no problems, all of which are headless except my Mac I code on. Headless won't have any effect on the script. 

I haven't had much time to look into it, and I'm going to need to sit down at my computer and see if I can figure it out. The exit error doesn't make it obvious to me what's even going wrong with it in your case.

**Comment by ghost** [comment] 2017-11-02 13:50
In a stroke of slight desperation 
Also because of my non-programmer status
I deleted the line that was causing the issue I have no idea what the long term effects of this will be but maybe it will work now by some miracle. Non of the models in my list are online. But it did go through the cycle twice.

**Comment by beaston02** [comment] 2017-11-02 13:53
Lol. Good to hear. I actually forgot about this. Do you know which line it was that you deleted? 

You could add a model who is currently online and see if it starts recording, then remove them, and restarting the script will terminate that recording.

**Comment by ghost** [comment] 2017-11-02 14:22
I don't think it is workingI've added a few models. 


0 model(s) are being recorded. Next check in 5 seconds
the following models are being recorded: []
So it cycles through that, but for some reason it never grabs any models. That line is probably more critical then I thought.

How would I check if my IP was blocked? Dont't know how to without a GUI

**Comment by beaston02** [comment] 2017-11-02 14:30
If it was line 26 you deleted, it is absolutely needed. It's the line which requests and reads the response from camsoda getting the json data for the online models. 

I don't think any of the lines aren't necessary and I don't think the script would function properly with any of them removed. 

You can run:
     curl https://www.camsoda.com

If your ip is blocked, then you will get a response of "Unauthorized" (inside some HTML code, probably a few lines total). If you aren't blocked, you will get pages of response which will be the HTML code for the main page you see if you went to camsoda a website in a web browser. 

Being blocked shouldn't throw an atrebute error though, it would cause a key error.

**Comment by ghost** [comment] 2017-11-02 14:32
It was line 80 actually

**Comment by beaston02** [comment] 2017-11-02 14:46
Line 80calls the "getOnlineModels" (or whatever it's exact name is) function defined earlier in the script. Line 26 is inside that function and the line which is causing the actual problem. By deleting line 80, the script will never execute line 26 because the function is never executed. 

Are you on reddit by chance? If so, message me there and I'll pm you another script to test, although I won't be able to send it until I get home later today. It's a non public rewrite I've done. Again, I have no idea why you're getting that error, and the new one uses that same line, or very similar, but maybe it will work for some reason.

My reddit name is the same as on here.

**Comment by ghost** [comment] 2017-11-02 14:49
Python is so confusing on Ubuntu.
So this line appears twice in your code  
print("the following models are being recorded: {}".format(recording), end="\r"
Basically it says syntax error  end="\r") when I try to use python2 instead of python3
                                                  ^
Deleting end=r makes the program run fine in python2

Somehow the code is broken on my python3 install not sure what going on because. I'm not sure because MFCRecorder Camster Chaturbate Camster all work with python3.

**Comment by ghost** [comment] 2017-11-02 14:51
I like to still try that test code. 
I have no idea how much destruction I caused y deleting that code. Though it working at this point

**Comment by beaston02** [comment] 2017-11-02 15:03
What's the output of:

     python3.5 --version

I generally run 3.5.2, but I believe I've tested most scripts with 3.6(.1??) also with no problems. 

The "end=\r" is saying to not go to the next line for the next print. That's used because the code will continuously print the output to the same lines so they are "refreshing" with the current info. It's not perfect, but I liked it better than constantly printing new lines. Others may or may not agree. Because of this method, and how I went about it, it may double up on some lines in the code.

**Comment by ghost** [comment] 2017-11-02 15:05
Python 3.5.2
Python2 is 2.7

**Comment by ghost** [comment] 2017-11-02 15:06
I have python3.6 install as well python 3.6.3

**Comment by beaston02** [comment] 2017-11-02 15:11
You could try running it with Python 3.6 and see if that makes a difference. 

I think I already suggested this earlier, but making sure requests is up to date, or maybe uninstalling and reinstalling it. 

     pip3 install -U requests

Should install the current version, I can't remember what's used to uninstall (might be uninstall, or remove) but google will tell you that pretty quickly. Then you could reinstall it. Again, I'm just not sure why you're seeing that error. This is just throwing ideas out there and hoping to get lucky.

**Comment by ghost** [comment] 2017-11-02 15:21
Hey we fix it

**Comment by beaston02** [comment] 2017-11-02 15:22
Lol. That did it? What was it you did that got it working? 

I hope you added line 80 back to it also...?

**Comment by ghost** [comment] 2017-11-02 15:32
So in the future, the issue is with the new version of the requests. 

  Installing collected packages: requests
  Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
it then defaulted to 2.18.4 which is the same one in python2. Which is why that one was working I believe.

**Comment by beaston02** [comment] 2017-11-02 15:34
Very good. Thank you for sharing. I'm glad it worked, and in going to go ahead and close this issue. If anyone else has this problem, I will now know the solution! 

Thank you for your patience and for working through it with me.

**Closed as completed by beaston02** 2017-11-02 15:34 UTC

**Comment by ghost** [comment] 2017-11-02 15:49
Hey and I figured out how to upgrade module 
since pip install just checks if the module is installed and doesn't check for upgrades/updates
Thanks for helping with that 

So I guess knowing what modules versions are installed are very with pip3 freeze or pip2 free is important

Also on second look, my module was out of date even though the number was higher. I  had never considered this. Whoever made it made the program requests. Has a confusing number scheme. Because they went for 2.9.1 all the way back to 2.11

**Comment by ericsantos1** [comment] 2019-04-13 05:46
Hi guys. I came across this problem, I run the camsoda script and it closes immediately. Something with line 80 and 26. I use python 3.7.3 and I already applied the indicated solution installing requests-2.11, but it did not work. I use windows 10.
![bug](https://user-images.githubusercontent.com/23618640/56075278-5ab80e00-5d96-11e9-9778-6fa2d62de2ea.png)

**Comment by RobertRosePeddles** [comment] 2022-01-30 09:11
hey boss u think u can help me get my account back. i think the i.p address got blocked so everytime i sign in usually it pretends i never logged on. as if the page refreshes. and yet still not logged in.
